# Project: Nhan Su
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o NhanSu.o GiaoVien.o
LINKOBJ  = main.o NhanSu.o GiaoVien.o
LIBS     = -L"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Users/24h/Dev-Cpp/MinGW64/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/24h/Dev-Cpp/MinGW64/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Nhan Su.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

NhanSu.o: NhanSu.cpp
	$(CPP) -c NhanSu.cpp -o NhanSu.o $(CXXFLAGS)

GiaoVien.o: GiaoVien.cpp
	$(CPP) -c GiaoVien.cpp -o GiaoVien.o $(CXXFLAGS)
