# Project: Publication
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Publication.o Book.o Tape.o
LINKOBJ  = main.o Publication.o Book.o Tape.o
LIBS     = -L"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Users/24h/Dev-Cpp/MinGW64/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/24h/Dev-Cpp/MinGW64/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/24h/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Publication.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Publication.o: Publication.cpp
	$(CPP) -c Publication.cpp -o Publication.o $(CXXFLAGS)

Book.o: Book.cpp
	$(CPP) -c Book.cpp -o Book.o $(CXXFLAGS)

Tape.o: Tape.cpp
	$(CPP) -c Tape.cpp -o Tape.o $(CXXFLAGS)
